//! Request IDs are generated by the server. A client may propagate one
//! (useful for tracing across our own services), but only a well-formed UUID
//! is accepted; anything else is dropped and replaced by a fresh id.
use axum::body::Body;
use axum::http::Request;
use axum::middleware::Next;
use axum::response::Response;

pub async fn sanitise(mut req: Request<Body>, next: Next) -> Response {
    let valid = req
        .headers()
        .get("x-request-id")
        .and_then(|v| v.to_str().ok())
        .is_some_and(|v| uuid::Uuid::parse_str(v).is_ok());
    if !valid {
        req.headers_mut().remove("x-request-id");
    }
    next.run(req).await
}
